sudo: required

language: python

services:
  - docker

install:
  - pip install yamllint
  - docker pull lukasmartinelli/hadolint
  - docker build -t lok-nexus .
  - docker run -d --net="host" -p 8081:8081 --restart=no --name lok-nexus lok-nexus; sleep 10

script:
  - docker run --rm -i lukasmartinelli/hadolint < Dockerfile
  - yamllint deployments/ services/
  - docker ps | grep -q lok-nexus
  - curl -s --retry-connrefused --retry 20 --retry-delay 10 -u admin:admin123 http://localhost:8081/service/metrics/ping | grep -q pong

notifications:
  slack:
    rooms:
      - secure: "jh6tG32VWctPJBZm1Q5x7AZ/HAbPgpM217rBweBaJzGGgQ86ea7Vg4nEH22o0qQJvQ3cf0nw/8IiUxOCTvGBrVxFfyCyKDmHQ5cDQwZeZlxFPl+uLvhxDOCMa7Rmp5f8xshTlHvSp9wMlzz/O78snLzBz0PDM6ygPa0vgXZxTMXOE9QWWRaTsUlxPMiQWDrhzEtO5qh8lTjbzt5jagMiRnNAxcjWLyd5QtxAhpT1pXe7EWdv/prD7dcn0EZKF2MxJDHUaHlxLD9rQgur0yZaaC6PosdWN5RUmLSi8IzgPTGTXfpLzt4KkFM8DVQwrUBeOHKKvBac68sOh5+B8/1scM033PGa1ER/QGZsi6rvZqcFnCSGaCOkYy214F1plMoq7S4iAtznMQkp51pa0tPA3x5vGSa/uMheS4cSEvyPRjIoucqxDn7EcqZljrWOJX0MIH9X18cWUwaoExr4pHQ3wio/9pSHAO11ERei4AGijKbGrb8tt8mUCUzCsZD4jMqTKI51uy0p5OEFvtsQN1UGbyABlsslKNQ2MUQXD4VBaCCP7+0zVsqLavUnIu3We4yt8fZoWMIFeL+nsCNVtYhBiq/8QzQuGAg2Eosivl9zaqqYJRs9J3MKBuXTwVC1KbRw12DL4VoKrdFRc8izMcdpAfaXBX74WtrI89TcjFs2J0I="
    on_success: change # default: always
    on_failure: change # default: always
    on_pull_requests: true # default: true

